controller_names:
  - position_trajectory_controller

position_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
      - joint1
      - joint2