controller_list:
  - name: fake_omron1s_manipulator_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
initial:  # Define initial robot poses.
  - group: omron1s_manipulator
    pose: home