omron1s_manipulator:
  # kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  # kinematics_solver_search_resolution: 0.005
  # kinematics_solver_timeout: 0.005
  # position_only_ik: true

  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  position_only_ik: true
  epsilon: 0.1
  # orientation_vs_position: -100

  # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  # kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin

  # kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  # # optional parameters for caching:
  # max_cache_size: 10000




  